# -*- coding: utf-8 -*-
"""4.2-Examples Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWhh81xcxc_78pYwocG470JzwpiPcf4-

#### Example 1: Temperature Conversion
"""

def convert_temperature(temp,unit):
    """This function converts temperature between Celsius and Fahrenheit"""
    if unit=='C':
        return temp * 9/5 + 32  ## Celsius To Fahrenheit
    elif unit=="F":
        return (temp-32)*5/9 ## Fahrenheit to celsius
    else:
        return None

print(convert_temperature(25,'C'))
print(convert_temperature(77,'F'))

"""##### Example 2: Password Strength Checker"""

def is_strong_password(password):
    """This function checks if the password is strong or not"""
    if len(password)<8:
        return False
    if not any(char.isdigit() for char in password):
        return False
    if not any(char.islower() for char in password):
        return False
    if not any(char.isupper() for char in password):
        return False
    if not any(char in '!@#$%^&*()_+' for char in password):
        return False
    return True

## calling the function
print(is_strong_password("WeakPwd"))
print(is_strong_password("Str0ngPwd!"))

"""##### Example 3: Calculate the Total Cost Of Items In a Shopping Cart"""

def calculate_total_cost(cart):
    total_cost=0
    for item in cart:
        total_cost+=item['price']* item['quantity']

    return total_cost


## Example cart data

cart=[
    {'name':'Apple','price':0.5,'quantity':4},
    {'name':'Banana','price':0.3,'quantity':6},
    {'name':'Orange','price':0.7,'quantity':3}

]

## calling the function
total_cost=calculate_total_cost(cart)
print(total_cost)

"""##### Example 4: Check IF a String Is Palindrome"""

def is_palindrome(s):
    s=s.lower().replace(" ","")
    return s==s[::-1]

print(is_palindrome("A man a plan a canal Panama"))
print(is_palindrome("Hello"))

"""##### Example 5: Calculate the factorials of a number using recursion"""

def factorial(n):
    if n==0:
        return 1
    else:
        return n * factorial(n-1)

print(factorial(6))

"""##### Example 6: A Function To Read A File and count the frequency of each word"""

def count_word_frequency(file_path):
    """A Function To Read A File and count the frequency of each word.
    If the specified file is not found, it will print an error message and return an empty dictionary.
    """
    word_count = {}
    try:
        with open(file_path, 'r') as file:
            for line in file:
                words = line.split()
                for word in words:
                    word = word.lower().strip('.,!?;:"\'')
                    word_count[word] = word_count.get(word, 0) + 1
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        # Consider returning an empty dictionary or raising the exception
        # depending on the desired behavior.
        return {}  # Returning an empty dictionary here.

    return word_count

filepath = 'sample.txt'
word_frequency = count_word_frequency(filepath)
print(word_frequency)

"""##### Example 7: Validate Email Address"""

import re

# Email validation function
def is_valid_email(email):
    """This function checks if the email is valid."""
    pattern = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    return re.match(pattern, email) is not None

# Calling the function
print(is_valid_email("test@example.com"))  # Output: True
print(is_valid_email("invalid-email"))  # Output: False