# -*- coding: utf-8 -*-
"""4.3-Lambda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RciS5AVGocEFNundWvtbPiKxA_eHCO8

### Lambda Functions in Python
Lambda functions are small anonymous functions defined using the **lambda** keyword. They can have any number of arguments but only one expression. They are commonly used for short operations or as arguments to higher-order functions.
"""

#Syntax
lambda arguments: expression

def addition(a,b):
    return a+b

addition(2,3)

addition=lambda a,b:a+b
type(addition)
print(addition(5,6))

addition=lambda a,b:a+b
type(addition)
print(addition(5,6))

even1=lambda num:num%2==0
even1(12)

def addition(x,y,z):
    return x+y+z

addition(12,13,14)

addition1=lambda x,y,z:x+y+z
addition1(12,13,14)

## map()- applies a function to all items in a list
numbers=[1,2,3,4,5,6]
def square(number):
    return number**2

square(2)

list(map(lambda x:x**2,numbers))