# -*- coding: utf-8 -*-
"""4.4-MapsFunction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RciS5AVGocEFNundWvtbPiKxA_eHCO8

### The map() Function in Python
The map() function applies a given function to all items in an input list (or any other iterable) and returns a map object (an iterator). This is particularly useful for transforming data in a list comprehensively.
"""

def square(x):
    return x*x

square(10)

numbers=[1,2,3,4,5,6,7,8]

list(map(square,numbers))

## Lambda function with map
numbers=[1,2,3,4,5,6,7,8]
list(map(lambda x:x*x,numbers))

### MAp multiple iterables

numbers1=[1,2,3]
numbers2=[4,5,6]

added_numbers=list(map(lambda x,y:x+y,numbers1,numbers2))
print(added_numbers)

## map() to convert a list of strings to integers
# Use map to convert strings to integers
str_numbers = ['1', '2', '3', '4', '5']
int_numbers = list(map(int, str_numbers))

print(int_numbers)  # Output: [1, 2, 3, 4, 5]

words=['apple','banana','cherry']
upper_word=list(map(str.upper,words))
print(upper_word)

def get_name(person):
    return person['name']

people=[
    {'name':'Adi','age':23},
    {'name':'Jack','age':33}
]
list(map(get_name,people))