# -*- coding: utf-8 -*-
"""4.5-Filterfunction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RciS5AVGocEFNundWvtbPiKxA_eHCO8

### The filter() Function in Python
The filter() function constructs an iterator from elements of an iterable for which a function returns true. It is used to filter out items from a list (or any other iterable) based on a condition.
"""

def even(num):
    if num%2==0:
        return True

even(24)

lst=[1,2,3,4,5,6,7,8,9,10,11,12]

list(filter(even,lst))

## filter with a Lambda Function
numbers=[1,2,3,4,5,6,7,8,9]
greater_than_five=list(filter(lambda x:x>5,numbers))
print(greater_than_five)

## Filter with a lambda function and multiple conditions
numbers=[1,2,3,4,5,6,7,8,9]
even_and_greater_than_five=list(filter(lambda x:x>5 and x%2==0,numbers))
print(even_and_greater_than_five)

## Filter() to check if the age is greate than 25 in dictionaries
people=[
    {'name':'Adi','age':23},
    {'name':'Jack','age':33},
    {'name':'John','age':25}
]

def age_greater_than_25(person):
    return person['age']>25

list(filter(age_greater_than_25,people))